# python FNCS_Volttron_Bridge.py fncs/input1 FNCS_VOLTTRON_Bridge1.config 1 &> FNCS_VOLTTRON_Bridge1.log & 
python FNCS_Volttron_Bridge.py fncs/input2 FNCS_VOLTTRON_Bridge2.config 2 &> FNCS_VOLTTRON_Bridge2.log & 
python FNCS_Volttron_Bridge.py fncs/input3 FNCS_VOLTTRON_Bridge3.config 3 &> FNCS_VOLTTRON_Bridge3.log & 
python FNCS_Volttron_Bridge.py fncs/input4 FNCS_VOLTTRON_Bridge4.config 4 &> FNCS_VOLTTRON_Bridge4.log & 
python FNCS_Volttron_Bridge.py fncs/input5 FNCS_VOLTTRON_Bridge5.config 5 &> FNCS_VOLTTRON_Bridge5.log & 
python FNCS_Volttron_Bridge.py fncs/input6 FNCS_VOLTTRON_Bridge6.config 6 &> FNCS_VOLTTRON_Bridge6.log & 
python FNCS_Volttron_Bridge.py fncs/input7 FNCS_VOLTTRON_Bridge7.config 7 &> FNCS_VOLTTRON_Bridge7.log & 
python FNCS_Volttron_Bridge.py fncs/input8 FNCS_VOLTTRON_Bridge8.config 8 &> FNCS_VOLTTRON_Bridge8.log & 
python FNCS_Volttron_Bridge.py fncs/input9 FNCS_VOLTTRON_Bridge9.config 9 &> FNCS_VOLTTRON_Bridge9.log & 
python FNCS_Volttron_Bridge.py fncs/input10 FNCS_VOLTTRON_Bridge10.config 10 &> FNCS_VOLTTRON_Bridge10.log & 
python FNCS_Volttron_Bridge.py fncs/input11 FNCS_VOLTTRON_Bridge11.config 11 &> FNCS_VOLTTRON_Bridge11.log & 
python FNCS_Volttron_Bridge.py fncs/input12 FNCS_VOLTTRON_Bridge12.config 12 &> FNCS_VOLTTRON_Bridge12.log & 
python FNCS_Volttron_Bridge.py fncs/input13 FNCS_VOLTTRON_Bridge13.config 13 &> FNCS_VOLTTRON_Bridge13.log & 
python FNCS_Volttron_Bridge.py fncs/input14 FNCS_VOLTTRON_Bridge14.config 14 &> FNCS_VOLTTRON_Bridge14.log & 
python FNCS_Volttron_Bridge.py fncs/input15 FNCS_VOLTTRON_Bridge15.config 15 &> FNCS_VOLTTRON_Bridge15.log & 
python FNCS_Volttron_Bridge.py fncs/input16 FNCS_VOLTTRON_Bridge16.config 16 &> FNCS_VOLTTRON_Bridge16.log & 
python FNCS_Volttron_Bridge.py fncs/input17 FNCS_VOLTTRON_Bridge17.config 17 &> FNCS_VOLTTRON_Bridge17.log & 
python FNCS_Volttron_Bridge.py fncs/input18 FNCS_VOLTTRON_Bridge18.config 18 &> FNCS_VOLTTRON_Bridge18.log & 
python FNCS_Volttron_Bridge.py fncs/input19 FNCS_VOLTTRON_Bridge19.config 19 &> FNCS_VOLTTRON_Bridge19.log & 
python FNCS_Volttron_Bridge.py fncs/input20 FNCS_VOLTTRON_Bridge20.config 20 &> FNCS_VOLTTRON_Bridge20.log & 
python FNCS_Volttron_Bridge.py fncs/input21 FNCS_VOLTTRON_Bridge21.config 21 &> FNCS_VOLTTRON_Bridge21.log & 
python FNCS_Volttron_Bridge.py fncs/input22 FNCS_VOLTTRON_Bridge22.config 22 &> FNCS_VOLTTRON_Bridge22.log & 
python FNCS_Volttron_Bridge.py fncs/input23 FNCS_VOLTTRON_Bridge23.config 23 &> FNCS_VOLTTRON_Bridge23.log & 
python FNCS_Volttron_Bridge.py fncs/input24 FNCS_VOLTTRON_Bridge24.config 24 &> FNCS_VOLTTRON_Bridge24.log & 
python FNCS_Volttron_Bridge.py fncs/input25 FNCS_VOLTTRON_Bridge25.config 25 &> FNCS_VOLTTRON_Bridge25.log & 
python FNCS_Volttron_Bridge.py fncs/input26 FNCS_VOLTTRON_Bridge26.config 26 &> FNCS_VOLTTRON_Bridge26.log & 
python FNCS_Volttron_Bridge.py fncs/input27 FNCS_VOLTTRON_Bridge27.config 27 &> FNCS_VOLTTRON_Bridge27.log & 
python FNCS_Volttron_Bridge.py fncs/input28 FNCS_VOLTTRON_Bridge28.config 28 &> FNCS_VOLTTRON_Bridge28.log & 
python FNCS_Volttron_Bridge.py fncs/input29 FNCS_VOLTTRON_Bridge29.config 29 &> FNCS_VOLTTRON_Bridge29.log & 
python FNCS_Volttron_Bridge.py fncs/input30 FNCS_VOLTTRON_Bridge30.config 30 &> FNCS_VOLTTRON_Bridge30.log & 
python FNCS_Volttron_Bridge.py fncs/input31 FNCS_VOLTTRON_Bridge31.config 31 &> FNCS_VOLTTRON_Bridge31.log & 
python FNCS_Volttron_Bridge.py fncs/input32 FNCS_VOLTTRON_Bridge32.config 32 &> FNCS_VOLTTRON_Bridge32.log & 
python FNCS_Volttron_Bridge.py fncs/input33 FNCS_VOLTTRON_Bridge33.config 33 &> FNCS_VOLTTRON_Bridge33.log & 
python FNCS_Volttron_Bridge.py fncs/input34 FNCS_VOLTTRON_Bridge34.config 34 &> FNCS_VOLTTRON_Bridge34.log & 
python FNCS_Volttron_Bridge.py fncs/input35 FNCS_VOLTTRON_Bridge35.config 35 &> FNCS_VOLTTRON_Bridge35.log & 
python FNCS_Volttron_Bridge.py fncs/input36 FNCS_VOLTTRON_Bridge36.config 36 &> FNCS_VOLTTRON_Bridge36.log & 
python FNCS_Volttron_Bridge.py fncs/input37 FNCS_VOLTTRON_Bridge37.config 37 &> FNCS_VOLTTRON_Bridge37.log & 
python FNCS_Volttron_Bridge.py fncs/input38 FNCS_VOLTTRON_Bridge38.config 38 &> FNCS_VOLTTRON_Bridge38.log & 
python FNCS_Volttron_Bridge.py fncs/input39 FNCS_VOLTTRON_Bridge39.config 39 &> FNCS_VOLTTRON_Bridge39.log & 
python FNCS_Volttron_Bridge.py fncs/input40 FNCS_VOLTTRON_Bridge40.config 40 &> FNCS_VOLTTRON_Bridge40.log & 
python FNCS_Volttron_Bridge.py fncs/input41 FNCS_VOLTTRON_Bridge41.config 41 &> FNCS_VOLTTRON_Bridge41.log & 
python FNCS_Volttron_Bridge.py fncs/input42 FNCS_VOLTTRON_Bridge42.config 42 &> FNCS_VOLTTRON_Bridge42.log & 
python FNCS_Volttron_Bridge.py fncs/input43 FNCS_VOLTTRON_Bridge43.config 43 &> FNCS_VOLTTRON_Bridge43.log & 
python FNCS_Volttron_Bridge.py fncs/input44 FNCS_VOLTTRON_Bridge44.config 44 &> FNCS_VOLTTRON_Bridge44.log & 
python FNCS_Volttron_Bridge.py fncs/input45 FNCS_VOLTTRON_Bridge45.config 45 &> FNCS_VOLTTRON_Bridge45.log & 
python FNCS_Volttron_Bridge.py fncs/input46 FNCS_VOLTTRON_Bridge46.config 46 &> FNCS_VOLTTRON_Bridge46.log & 
python FNCS_Volttron_Bridge.py fncs/input47 FNCS_VOLTTRON_Bridge47.config 47 &> FNCS_VOLTTRON_Bridge47.log & 
python FNCS_Volttron_Bridge.py fncs/input48 FNCS_VOLTTRON_Bridge48.config 48 &> FNCS_VOLTTRON_Bridge48.log & 
python FNCS_Volttron_Bridge.py fncs/input49 FNCS_VOLTTRON_Bridge49.config 49 &> FNCS_VOLTTRON_Bridge49.log & 
python FNCS_Volttron_Bridge.py fncs/input50 FNCS_VOLTTRON_Bridge50.config 50 &> FNCS_VOLTTRON_Bridge50.log & 
python FNCS_Volttron_Bridge.py fncs/input51 FNCS_VOLTTRON_Bridge51.config 51 &> FNCS_VOLTTRON_Bridge51.log & 
python FNCS_Volttron_Bridge.py fncs/input52 FNCS_VOLTTRON_Bridge52.config 52 &> FNCS_VOLTTRON_Bridge52.log & 
python FNCS_Volttron_Bridge.py fncs/input53 FNCS_VOLTTRON_Bridge53.config 53 &> FNCS_VOLTTRON_Bridge53.log & 
python FNCS_Volttron_Bridge.py fncs/input54 FNCS_VOLTTRON_Bridge54.config 54 &> FNCS_VOLTTRON_Bridge54.log & 
python FNCS_Volttron_Bridge.py fncs/input55 FNCS_VOLTTRON_Bridge55.config 55 &> FNCS_VOLTTRON_Bridge55.log & 
python FNCS_Volttron_Bridge.py fncs/input56 FNCS_VOLTTRON_Bridge56.config 56 &> FNCS_VOLTTRON_Bridge56.log & 
python FNCS_Volttron_Bridge.py fncs/input57 FNCS_VOLTTRON_Bridge57.config 57 &> FNCS_VOLTTRON_Bridge57.log & 
python FNCS_Volttron_Bridge.py fncs/input58 FNCS_VOLTTRON_Bridge58.config 58 &> FNCS_VOLTTRON_Bridge58.log & 
python FNCS_Volttron_Bridge.py fncs/input59 FNCS_VOLTTRON_Bridge59.config 59 &> FNCS_VOLTTRON_Bridge59.log & 
python FNCS_Volttron_Bridge.py fncs/input60 FNCS_VOLTTRON_Bridge60.config 60 &> FNCS_VOLTTRON_Bridge60.log & 
python FNCS_Volttron_Bridge.py fncs/input61 FNCS_VOLTTRON_Bridge61.config 61 &> FNCS_VOLTTRON_Bridge61.log & 
python FNCS_Volttron_Bridge.py fncs/input62 FNCS_VOLTTRON_Bridge62.config 62 &> FNCS_VOLTTRON_Bridge62.log & 
python FNCS_Volttron_Bridge.py fncs/input63 FNCS_VOLTTRON_Bridge63.config 63 &> FNCS_VOLTTRON_Bridge63.log & 
python FNCS_Volttron_Bridge.py fncs/input64 FNCS_VOLTTRON_Bridge64.config 64 &> FNCS_VOLTTRON_Bridge64.log & 
python FNCS_Volttron_Bridge.py fncs/input65 FNCS_VOLTTRON_Bridge65.config 65 &> FNCS_VOLTTRON_Bridge65.log & 
python FNCS_Volttron_Bridge.py fncs/input66 FNCS_VOLTTRON_Bridge66.config 66 &> FNCS_VOLTTRON_Bridge66.log & 
python FNCS_Volttron_Bridge.py fncs/input67 FNCS_VOLTTRON_Bridge67.config 67 &> FNCS_VOLTTRON_Bridge67.log & 
python FNCS_Volttron_Bridge.py fncs/input68 FNCS_VOLTTRON_Bridge68.config 68 &> FNCS_VOLTTRON_Bridge68.log & 
python FNCS_Volttron_Bridge.py fncs/input69 FNCS_VOLTTRON_Bridge69.config 69 &> FNCS_VOLTTRON_Bridge69.log & 
python FNCS_Volttron_Bridge.py fncs/input70 FNCS_VOLTTRON_Bridge70.config 70 &> FNCS_VOLTTRON_Bridge70.log & 
python FNCS_Volttron_Bridge.py fncs/input71 FNCS_VOLTTRON_Bridge71.config 71 &> FNCS_VOLTTRON_Bridge71.log & 
python FNCS_Volttron_Bridge.py fncs/input72 FNCS_VOLTTRON_Bridge72.config 72 &> FNCS_VOLTTRON_Bridge72.log & 
python FNCS_Volttron_Bridge.py fncs/input73 FNCS_VOLTTRON_Bridge73.config 73 &> FNCS_VOLTTRON_Bridge73.log & 
python FNCS_Volttron_Bridge.py fncs/input74 FNCS_VOLTTRON_Bridge74.config 74 &> FNCS_VOLTTRON_Bridge74.log & 
python FNCS_Volttron_Bridge.py fncs/input75 FNCS_VOLTTRON_Bridge75.config 75 &> FNCS_VOLTTRON_Bridge75.log & 
python FNCS_Volttron_Bridge.py fncs/input76 FNCS_VOLTTRON_Bridge76.config 76 &> FNCS_VOLTTRON_Bridge76.log & 
python FNCS_Volttron_Bridge.py fncs/input77 FNCS_VOLTTRON_Bridge77.config 77 &> FNCS_VOLTTRON_Bridge77.log & 
python FNCS_Volttron_Bridge.py fncs/input78 FNCS_VOLTTRON_Bridge78.config 78 &> FNCS_VOLTTRON_Bridge78.log & 
python FNCS_Volttron_Bridge.py fncs/input79 FNCS_VOLTTRON_Bridge79.config 79 &> FNCS_VOLTTRON_Bridge79.log & 
python FNCS_Volttron_Bridge.py fncs/input80 FNCS_VOLTTRON_Bridge80.config 80 &> FNCS_VOLTTRON_Bridge80.log & 
python FNCS_Volttron_Bridge.py fncs/input81 FNCS_VOLTTRON_Bridge81.config 81 &> FNCS_VOLTTRON_Bridge81.log & 
python FNCS_Volttron_Bridge.py fncs/input82 FNCS_VOLTTRON_Bridge82.config 82 &> FNCS_VOLTTRON_Bridge82.log & 
python FNCS_Volttron_Bridge.py fncs/input83 FNCS_VOLTTRON_Bridge83.config 83 &> FNCS_VOLTTRON_Bridge83.log & 
python FNCS_Volttron_Bridge.py fncs/input84 FNCS_VOLTTRON_Bridge84.config 84 &> FNCS_VOLTTRON_Bridge84.log & 
python FNCS_Volttron_Bridge.py fncs/input85 FNCS_VOLTTRON_Bridge85.config 85 &> FNCS_VOLTTRON_Bridge85.log & 
python FNCS_Volttron_Bridge.py fncs/input86 FNCS_VOLTTRON_Bridge86.config 86 &> FNCS_VOLTTRON_Bridge86.log & 
python FNCS_Volttron_Bridge.py fncs/input87 FNCS_VOLTTRON_Bridge87.config 87 &> FNCS_VOLTTRON_Bridge87.log & 
python FNCS_Volttron_Bridge.py fncs/input88 FNCS_VOLTTRON_Bridge88.config 88 &> FNCS_VOLTTRON_Bridge88.log & 
python FNCS_Volttron_Bridge.py fncs/input89 FNCS_VOLTTRON_Bridge89.config 89 &> FNCS_VOLTTRON_Bridge89.log & 
python FNCS_Volttron_Bridge.py fncs/input90 FNCS_VOLTTRON_Bridge90.config 90 &> FNCS_VOLTTRON_Bridge90.log & 
python FNCS_Volttron_Bridge.py fncs/input91 FNCS_VOLTTRON_Bridge91.config 91 &> FNCS_VOLTTRON_Bridge91.log & 
python FNCS_Volttron_Bridge.py fncs/input92 FNCS_VOLTTRON_Bridge92.config 92 &> FNCS_VOLTTRON_Bridge92.log & 
python FNCS_Volttron_Bridge.py fncs/input93 FNCS_VOLTTRON_Bridge93.config 93 &> FNCS_VOLTTRON_Bridge93.log & 
python FNCS_Volttron_Bridge.py fncs/input94 FNCS_VOLTTRON_Bridge94.config 94 &> FNCS_VOLTTRON_Bridge94.log & 
python FNCS_Volttron_Bridge.py fncs/input95 FNCS_VOLTTRON_Bridge95.config 95 &> FNCS_VOLTTRON_Bridge95.log & 
python FNCS_Volttron_Bridge.py fncs/input96 FNCS_VOLTTRON_Bridge96.config 96 &> FNCS_VOLTTRON_Bridge96.log & 
python FNCS_Volttron_Bridge.py fncs/input97 FNCS_VOLTTRON_Bridge97.config 97 &> FNCS_VOLTTRON_Bridge97.log & 
python FNCS_Volttron_Bridge.py fncs/input98 FNCS_VOLTTRON_Bridge98.config 98 &> FNCS_VOLTTRON_Bridge98.log & 
python FNCS_Volttron_Bridge.py fncs/input99 FNCS_VOLTTRON_Bridge99.config 99 &> FNCS_VOLTTRON_Bridge99.log & 
python FNCS_Volttron_Bridge.py fncs/input100 FNCS_VOLTTRON_Bridge100.config 100 &> FNCS_VOLTTRON_Bridge100.log & 
python FNCS_Volttron_Bridge.py fncs/input101 FNCS_VOLTTRON_Bridge101.config 101 &> FNCS_VOLTTRON_Bridge101.log & 
python FNCS_Volttron_Bridge.py fncs/input102 FNCS_VOLTTRON_Bridge102.config 102 &> FNCS_VOLTTRON_Bridge102.log & 
python FNCS_Volttron_Bridge.py fncs/input103 FNCS_VOLTTRON_Bridge103.config 103 &> FNCS_VOLTTRON_Bridge103.log & 
python FNCS_Volttron_Bridge.py fncs/input104 FNCS_VOLTTRON_Bridge104.config 104 &> FNCS_VOLTTRON_Bridge104.log & 
